// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7qBFIhAGAK4foegjjGWUvmkcOH-6zrr8',
    appId: '1:755239370984:web:af1ac6d7b5ad74f8c3895d',
    messagingSenderId: '755239370984',
    projectId: 'gym-tracker-3f423',
    authDomain: 'gym-tracker-3f423.firebaseapp.com',
    storageBucket: 'gym-tracker-3f423.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANjeTxgr5GkVVS9yw4Pd1QaZA-Q2vz8Oo',
    appId: '1:755239370984:android:f4f0b57a74ffc363c3895d',
    messagingSenderId: '755239370984',
    projectId: 'gym-tracker-3f423',
    storageBucket: 'gym-tracker-3f423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnwM13w1-Cf6KgMbqx3tql7VsYCeVUSY0',
    appId: '1:755239370984:ios:83f2a89b9bbf034ac3895d',
    messagingSenderId: '755239370984',
    projectId: 'gym-tracker-3f423',
    storageBucket: 'gym-tracker-3f423.firebasestorage.app',
    iosBundleId: 'com.example.gymTrackerApp',
  );

}